peer_id = 0
ctrl_port = 50051
proxy_port = 8081
servers = [ "localhost:6379", "localhost:6378" ]

[[peers]]
  addr = "http://[::1]:50051"
  id = 0
[[peers]]
  addr = "http://[::1]:50052"
  id = 1
[[peers]]
  addr = "http://[::1]:50053"
  id = 2
