peer_id = 1
ctrl_port = 50052
proxy_port = 8082
servers = [ "vk1:6379", "vk2:6379" ]

[[peers]]
  addr = "http://[::1]:50051"
  id = 0
[[peers]]
  addr = "http://[::1]:50052"
  id = 1
[[peers]]
  addr = "http://[::1]:50053"
  id = 2
